import { Metadata } from "next";
import { ResultsNav } from "../components/Nav/ResultsNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="font-sans h-screen fixed inset-0 flex flex-col items-center bg-background sm:py-4">
      <div className="flex flex-col max-w-[40rem] size-full border-4 border-theme-light sm:rounded-xl overflow-hidden">
        <header className="bg-theme-light py-6 flex flex-col items-center text-theme-dark">
          <h1 className="font-display uppercase text-xl">Strikeout</h1>
          <h2 className="uppercase font-bold">
            <svg
              width="17"
              height="17"
              viewBox="0 0 17 17"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="inline-block"
            >
              <path
                d="M8.03223 0.5L9.44644 7.08579L16.0322 8.5L9.44644 9.91421L8.03223 16.5L6.61801 9.91421L0.0322266 8.5L6.61801 7.08579L8.03223 0.5Z"
                fill="#100F12"
              />
            </svg>
            Final Round
            <svg
              width="17"
              height="17"
              viewBox="0 0 17 17"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="inline-block"
            >
              <path
                d="M8.03223 0.5L9.44644 7.08579L16.0322 8.5L9.44644 9.91421L8.03223 16.5L6.61801 9.91421L0.0322266 8.5L6.61801 7.08579L8.03223 0.5Z"
                fill="#100F12"
              />
            </svg>
          </h2>
        </header>
        <main className="bg-background flex flex-col px-6 py-6 h-full overflow-auto">
          {children}
        </main>
        <ResultsNav />
      </div>
    </div>
  );
}
